name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Func
      id: func
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Func
        setup-command: ''
        command: javac -cp utilities/antlr-4.13.1-complete.jar -d out $(find src gen
          -name "*.java") && java -cp out:utilities/antlr-4.13.1-complete.jar SimpleLang
          tests/01-func.cpy
        input: ''
        expected-output: |
          ####Statements####
          func foo: 1
          func main: 2

          ####Expressions####
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: For
      id: for
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: For
        setup-command: ''
        command: javac -cp utilities/antlr-4.13.1-complete.jar -d out $(find src gen
          -name "*.java") && java -cp out:utilities/antlr-4.13.1-complete.jar SimpleLang
          tests/02-for.cpy
        input: ''
        expected-output: |
          ####Statements####
          func main: 2
          for: 2

          ####Expressions####
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: If
      id: if
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: If
        setup-command: ''
        command: javac -cp utilities/antlr-4.13.1-complete.jar -d out $(find src gen
          -name "*.java") && java -cp out:utilities/antlr-4.13.1-complete.jar SimpleLang
          tests/03-if.cpy
        input: ''
        expected-output: |
          ####Statements####
          func main: 4
          if: 1 2 3

          ####Expressions####
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: While
      id: while
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: While
        setup-command: ''
        command: javac -cp utilities/antlr-4.13.1-complete.jar -d out $(find src gen
          -name "*.java") && java -cp out:utilities/antlr-4.13.1-complete.jar SimpleLang
          tests/04-while.cpy
        input: ''
        expected-output: |
          ####Statements####
          func main: 2
          while: 2

          ####Expressions####
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Nested
      id: nested
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Nested
        setup-command: ''
        command: javac -cp utilities/antlr-4.13.1-complete.jar -d out $(find src gen
          -name "*.java") && java -cp out:utilities/antlr-4.13.1-complete.jar SimpleLang
          tests/05-nested.cpy
        input: ''
        expected-output: |
          ####Statements####
          func main: 2
          for: 5
          if: 1 2 3
          while: 0

          ####Expressions####
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Binary Exp
      id: binary-exp
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Binary Exp
        setup-command: ''
        command: javac -cp utilities/antlr-4.13.1-complete.jar -d out $(find src gen
          -name "*.java") && java -cp out:utilities/antlr-4.13.1-complete.jar SimpleLang
          tests/06-binery_exp.cpy
        input: ''
        expected-output: |-
          ####Statements####
          func main: 3

          ####Expressions####
          +: 1
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Unary Exp
      id: unary-exp
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Unary Exp
        setup-command: ''
        command: javac -cp utilities/antlr-4.13.1-complete.jar -d out $(find src gen
          -name "*.java") && java -cp out:utilities/antlr-4.13.1-complete.jar SimpleLang
          tests/07-unery_exp.cpy
        input: ''
        expected-output: |-
          ####Statements####
          func main: 3

          ####Expressions####
          ++: 1
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Binary Exp 2
      id: binary-exp-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Binary Exp 2
        setup-command: ''
        command: javac -cp utilities/antlr-4.13.1-complete.jar -d out $(find src gen
          -name "*.java") && java -cp out:utilities/antlr-4.13.1-complete.jar SimpleLang
          tests/08-binery_exp2.cpy
        input: ''
        expected-output: |-
          ####Statements####
          func main: 3

          ####Expressions####
          +=: 1
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Binary Exp Long
      id: binary-exp-long
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Binary Exp Long
        setup-command: ''
        command: javac -cp utilities/antlr-4.13.1-complete.jar -d out $(find src gen
          -name "*.java") && java -cp out:utilities/antlr-4.13.1-complete.jar SimpleLang
          tests/09-binery_exp_long.cpy
        input: ''
        expected-output: |-
          ####Statements####
          func main: 3

          ####Expressions####
          +: 2
          -: 1
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Mix Exp
      id: mix-exp
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Mix Exp
        setup-command: ''
        command: javac -cp utilities/antlr-4.13.1-complete.jar -d out $(find src gen
          -name "*.java") && java -cp out:utilities/antlr-4.13.1-complete.jar SimpleLang
          tests/10-mix_exp.cpy
        input: ''
        expected-output: |-
          ####Statements####
          func main: 3

          ####Expressions####
          *=: 5
          -: 4
          +: 3
          ++: 1
          *: 2
          --: 1
          +=: 1
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Program
      id: program
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Program
        setup-command: ''
        command: javac -cp utilities/antlr-4.13.1-complete.jar -d out $(find src gen
          -name "*.java") && java -cp out:utilities/antlr-4.13.1-complete.jar SimpleLang
          tests/11-program.cpy
        input: ''
        expected-output: |-
          ####Statements####
          func reverseNumber: 3
          while: 2
          func main: 8
          if: 2
          if: 1 1

          ####Expressions####
          >: 1
          +: 2
          *: 1
          %: 1
          /=: 1
          &: 1
          <: 1
          ==: 1
        comparison-method: contains
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        FUNC_RESULTS: "${{steps.func.outputs.result}}"
        FOR_RESULTS: "${{steps.for.outputs.result}}"
        IF_RESULTS: "${{steps.if.outputs.result}}"
        WHILE_RESULTS: "${{steps.while.outputs.result}}"
        NESTED_RESULTS: "${{steps.nested.outputs.result}}"
        BINARY-EXP_RESULTS: "${{steps.binary-exp.outputs.result}}"
        UNARY-EXP_RESULTS: "${{steps.unary-exp.outputs.result}}"
        BINARY-EXP-2_RESULTS: "${{steps.binary-exp-2.outputs.result}}"
        BINARY-EXP-LONG_RESULTS: "${{steps.binary-exp-long.outputs.result}}"
        MIX-EXP_RESULTS: "${{steps.mix-exp.outputs.result}}"
        PROGRAM_RESULTS: "${{steps.program.outputs.result}}"
      with:
        runners: func,for,if,while,nested,binary-exp,unary-exp,binary-exp-2,binary-exp-long,mix-exp,program
